name: Deploy on Push

on: [push]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: check out the code to bulid server
        uses: actions/checkout@v4
      - name: copy file to server
        uses: appleboy/scp-action@master 
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER_NAME}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SHH_KEY}}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1

      